language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck
      - cmake
      - gcc-4.8

before_install:
  - sudo pip install cpplint

script:
  - cmake CMakeLists.txt && make
  - cppcheck --enable=all ./grepc
  - cpplint grepc/* --extensions=cc,h
  - bash test/functional/run.sh